FROM node:24.4-bullseye

WORKDIR /app

COPY package.json ./
RUN npm install --include=dev

# Copy the rest of the application code
COPY . .

# Expose the development port
EXPOSE 3000

# Command to run the Next.js development server
CMD ["npm", "run", "dev"]
