import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import DefaultBar from "@/components/default-bar";
import Providers from './providers';
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from 'next/headers';
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const notoThai = Noto_Sans_Thai({
  subsets: ['thai'],  // include Thai glyphs
  weight: ['400', '700'], // choose available font weights
  variable: '--font-noto-thai', // optional CSS variable
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type User = {
  username: string,
  isp: string | null
}

type Refresh = {
  access: string,
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    let access = cookieStore.get('access')?.value;
    let user: User | null = null;

    if (access) {
      const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND}/api/user/users/me/`, {
        method: 'GET',
        headers: { Authorization: `Bearer ${access}` },
      });
      if (res.ok) {
        const resJson: User = await res.json();
        user = resJson;
      }
    }


  return (
    // <html lang="en" suppressHydrationWarning>
      <html lang="th" className={notoThai.className} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem={false} // Disable system theme detection
        forcedTheme="light" // Force the theme to always be light
        disableTransitionOnChange
      >
          <div className="w-full min-h-full relative">
              <Providers>
                <SidebarProvider>
                  <DefaultBar user={user ?? null}>
                    {children}
                  </DefaultBar>
                </SidebarProvider>
              </Providers>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
