# Generated by Django 4.2.24 on 2025-11-08 08:53

import core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores. No spaces or special characters.', regex='^[a-zA-Z0-9_]+$')])),
                ('given_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('family_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('thaiid', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=32)),
                ('path', models.URLField(max_length=2000)),
                ('activity', models.CharField(choices=[('Login', 'login'), ('Logout', 'logout'), ('Visit', 'visit'), ('Download', 'download')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(default=0, editable=False, unique=True)),
                ('order_no', models.CharField(default=None, editable=False, max_length=32, unique=True)),
                ('order_list', models.CharField(default=None, editable=False, max_length=32, null=True)),
                ('order_date', models.DateField(editable=False, null=True)),
                ('order_filename', models.CharField(default=None, editable=False, max_length=256, null=True)),
                ('orderred_no', models.CharField(default=None, editable=False, max_length=32, null=True)),
                ('orderred_date', models.DateField(default=None, editable=False, null=True)),
                ('orderblack_no', models.CharField(default=None, editable=False, max_length=32, null=True)),
                ('orderblack_date', models.DateField(default=None, editable=False, null=True)),
                ('isp_no', models.CharField(default=None, editable=False, max_length=32, null=True)),
                ('isp_date', models.DateField(default=None, editable=False, null=True)),
                ('kind_id', models.PositiveIntegerField(default=None, editable=False, null=True)),
                ('kind_name', models.CharField(default=None, editable=False, max_length=128, null=True)),
                ('createdate', models.DateTimeField(default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=2000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.document_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document_no', models.CharField(blank=True, max_length=32)),
                ('document_date', models.DateTimeField(null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField(blank=True, default='')),
                ('speed', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('secret', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.group_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls'])])),
                ('all_isp', models.BooleanField(default=False, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('isp_id', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('kind_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmed_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('fail', 'Fail'), ('idle', 'Idle')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.mail_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls'])])),
                ('all_isp', models.BooleanField(default=False, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField(blank=True, default='')),
                ('speed', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('secret', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('document_no', models.CharField(blank=True, max_length=32)),
                ('document_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('id_address', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='core.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_tag_name_ci'),
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailgroup',
            name='documents',
            field=models.ManyToManyField(editable=False, related_name='mailgroups', to='core.document'),
        ),
        migrations.AddField(
            model_name='mailgroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailgroups', to='core.group'),
        ),
        migrations.AddField(
            model_name='mailgroup',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailgroups', to='core.section'),
        ),
        migrations.AddField(
            model_name='mailgroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailfile',
            name='isp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.isp'),
        ),
        migrations.AddField(
            model_name='mailfile',
            name='mail_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mail_files', to='core.mailgroup'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_files',
            field=models.ManyToManyField(related_name='mails', to='core.mailfile'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='core.mailgroup'),
        ),
        migrations.AddField(
            model_name='mail',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='kind',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_kind_name_ci'),
        ),
        migrations.AddField(
            model_name='isp',
            name='documents',
            field=models.ManyToManyField(related_name='isps', to='core.document'),
        ),
        migrations.AddField(
            model_name='groupfile',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_files', to='core.group'),
        ),
        migrations.AddField(
            model_name='groupfile',
            name='isp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.isp'),
        ),
        migrations.AddField(
            model_name='groupdocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.AddField(
            model_name='groupdocument',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AddField(
            model_name='groupdocument',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='documents',
            field=models.ManyToManyField(related_name='document_groups', through='core.GroupDocument', to='core.document'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.section'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_file', to='core.document'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name_ci'),
        ),
        migrations.AddField(
            model_name='activity',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.AddField(
            model_name='activity',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documentfile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='isp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.isp'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='isp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.isp'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_section_name_user_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('given_name', 'family_name', 'birthdate'), name='unique_given_name_family_name_birthdate'),
        ),
    ]
